### ISSUE TITLE
Look at column order for seeding CSV data

### ISSUE THREAD

**Issue by thfis-dfds** [dfds/pgup#1]
See https://stackoverflow.com/questions/38302721/copy-column-order for inspiration.

**Comment by avnes** [comment]
@thfis-dfds If this is still relevant, we are happy to take a pull request from you on it. If it is not relevant, can this issue be closed?

**Comment by thfis-dfds** [comment]
To be honest, I haven't looked at this for a while, and I don't even remember the reason behind. I'll just close it.
